// Compact K-OSM basemap for the Seun static viewer.
//
// The source is a bounded, same-origin snapshot generated by
// scripts/fetch-kosm-snapshot.mjs. Keeping the tiles local avoids the public
// K-OSM endpoint's origin restriction and makes the experimental branch work
// in local preview and static hosting alike.

const SOURCE = "kosm";
const sourceLayer = (name) => ({ source: SOURCE, "source-layer": name });

const LEVELS = ["to-number", ["get", "building:levels"], 0];
const SURVEYED_HEIGHT = ["to-number", ["get", "height"], 0];
const TOTAL_AREA = ["to-number", ["get", "building:area:total"], 0];
const GROUND_AREA = ["to-number", ["get", "building:area:ground"], 0];
const AREA_LEVELS = ["/", TOTAL_AREA, ["max", GROUND_AREA, 1]];

export const KOSM_LEVEL_HEIGHT_STOPS = [
  [1, 4.9], [2, 7.8], [3, 10.5], [5, 15], [10, 29.9],
  [15, 41.3], [20, 55.2], [30, 86.8], [40, 118.8], [60, 182.8],
];

// K-OSM's Korea-calibrated level curve. A building with no usable scale
// attributes stays visible with a conservative one-storey context height;
// its detail panel explicitly marks that height as a visual fallback.
export const KOSM_BUILDING_HEIGHT = [
  "case",
  [">", SURVEYED_HEIGHT, 0],
  SURVEYED_HEIGHT,
  [">", LEVELS, 0],
  [
    "interpolate",
    ["linear"],
    LEVELS,
    ...KOSM_LEVEL_HEIGHT_STOPS.flat(),
  ],
  ["all", [">", TOTAL_AREA, 0], [">", GROUND_AREA, 0]],
  ["*", 3, ["max", 1, ["min", 30, AREA_LEVELS]]],
  4.9,
];

function interpolateKosmHeight(levels) {
  if (levels <= KOSM_LEVEL_HEIGHT_STOPS[0][0]) {
    return KOSM_LEVEL_HEIGHT_STOPS[0][1];
  }
  for (let index = 1; index < KOSM_LEVEL_HEIGHT_STOPS.length; index += 1) {
    const [rightLevel, rightHeight] = KOSM_LEVEL_HEIGHT_STOPS[index];
    const [leftLevel, leftHeight] = KOSM_LEVEL_HEIGHT_STOPS[index - 1];
    if (levels > rightLevel) continue;
    const t = (levels - leftLevel) / (rightLevel - leftLevel);
    return leftHeight + t * (rightHeight - leftHeight);
  }
  return KOSM_LEVEL_HEIGHT_STOPS.at(-1)[1];
}

/** Resolve the same scale model used by the extrusion into panel-ready facts. */
export function estimateKosmBuildingScale(properties = {}) {
  const measuredHeight = Number(properties.height);
  const floors = Number(properties["building:levels"]);
  const grossFloorArea = Number(properties["building:area:total"]);
  const footprintArea = Number(properties["building:area:ground"]);
  let height = 4.9;
  let heightBasis = "규모 정보 없음 · 4.9m 시각화 기본값";

  if (Number.isFinite(measuredHeight) && measuredHeight > 0) {
    height = measuredHeight;
    heightBasis = "K-OSM 실측 높이";
  } else if (Number.isFinite(floors) && floors > 0) {
    height = interpolateKosmHeight(floors);
    heightBasis = "K-OSM 층수 기반 추정";
  } else if (
    Number.isFinite(grossFloorArea) && grossFloorArea > 0 &&
    Number.isFinite(footprintArea) && footprintArea > 0
  ) {
    height = Math.max(1, Math.min(30, grossFloorArea / footprintArea)) * 3;
    heightBasis = "K-OSM 연면적 ÷ 건축면적 기반 추정";
  }

  return {
    floors: Number.isFinite(floors) && floors > 0 ? floors : null,
    heightM: Number(height.toFixed(1)),
    heightBasis,
    footprintAreaM2:
      Number.isFinite(footprintArea) && footprintArea > 0 ? footprintArea : null,
    grossFloorAreaM2:
      Number.isFinite(grossFloorArea) && grossFloorArea > 0 ? grossFloorArea : null,
  };
}

const classFilter = (values) => [
  "match",
  ["get", "class"],
  values,
  true,
  false,
];

const lineLayer = (id, values, color, casing, minzoom = 12) => ({
  id,
  type: "line",
  ...sourceLayer("transportation"),
  minzoom,
  filter: classFilter(values),
  layout: { "line-cap": casing ? "butt" : "round", "line-join": "round" },
  paint: {
    "line-color": color,
    "line-width": [
      "interpolate",
      ["exponential", 1.4],
      ["zoom"],
      12, casing ? 0.9 : 0.5,
      14, casing ? 3.2 : 2,
      16, casing ? 7 : 5,
      18, casing ? 17 : 14,
    ],
  },
});

const minor = ["residential", "living_street", "unclassified", "service", "road"];
const secondary = ["secondary", "secondary_link", "tertiary", "tertiary_link"];
const primary = ["primary", "primary_link"];
const major = ["motorway", "motorway_link", "trunk", "trunk_link"];

export function buildKosmStyle(bounds = undefined) {
  const tileRoot = new URL("../data/kosm-tiles/", import.meta.url).href;
  const fontRoot = new URL("../data/kosm-fonts/", import.meta.url).href;

  return {
    version: 8,
    name: "K-OSM · Seun experimental snapshot",
    glyphs: `${fontRoot}{fontstack}/{range}.pbf`,
    sources: {
      [SOURCE]: {
        type: "vector",
        tiles: [`${tileRoot}{z}/{x}/{y}.mvt`],
        minzoom: 12,
        maxzoom: 16,
        ...(Array.isArray(bounds) && bounds.length === 4 ? { bounds } : {}),
        attribution: "© K-OSM · © OpenStreetMap contributors",
      },
    },
    layers: [
      {
        id: "background",
        type: "background",
        paint: { "background-color": "#f7f7f4" },
      },
      {
        id: "park",
        type: "fill",
        ...sourceLayer("park"),
        paint: { "fill-color": "#d9e8cd", "fill-opacity": 0.82 },
      },
      {
        id: "area-feature",
        type: "fill",
        ...sourceLayer("area_feature"),
        filter: ["!=", ["get", "class"], "highway"],
        paint: { "fill-color": "#e3ded5", "fill-outline-color": "#dbd6cd" },
      },
      {
        id: "water",
        type: "fill",
        ...sourceLayer("water"),
        paint: { "fill-color": "#aad3df" },
      },
      {
        id: "building",
        type: "fill",
        ...sourceLayer("building"),
        minzoom: 14,
        paint: { "fill-color": "#e9e6e0", "fill-outline-color": "#d3cec6" },
      },
      lineLayer("road-minor-casing", minor, "#e3ded5", true, 13),
      lineLayer("road-secondary-casing", secondary, "#ddd8cf", true, 12),
      lineLayer("road-primary-casing", primary, "#e6d1a8", true, 11),
      lineLayer("road-major-casing", major, "#dda568", true, 9),
      lineLayer("road-minor", minor, "#ffffff", false, 12),
      lineLayer("road-secondary", secondary, "#ffffff", false, 10),
      lineLayer("road-primary", primary, "#fbe7c4", false, 8),
      lineLayer("road-major", major, "#f4c48a", false, 5),
      {
        id: "railway",
        type: "line",
        ...sourceLayer("transportation"),
        minzoom: 11,
        filter: ["has", "railway"],
        paint: {
          "line-color": "#aaa59d",
          "line-width": ["interpolate", ["linear"], ["zoom"], 11, 0.6, 18, 2.5],
          "line-dasharray": [4, 3],
        },
      },
      {
        // Template consumed by main.js to construct the zone-masked surround.
        id: "building-3d",
        type: "fill-extrusion",
        ...sourceLayer("building"),
        minzoom: 14,
        paint: {
          "fill-extrusion-color": "#dcd8d1",
          "fill-extrusion-height": KOSM_BUILDING_HEIGHT,
          "fill-extrusion-base": 0,
          "fill-extrusion-opacity": 0.7,
          "fill-extrusion-vertical-gradient": true,
        },
      },
      {
        id: "road-label",
        type: "symbol",
        ...sourceLayer("transportation"),
        minzoom: 14,
        filter: ["has", "name"],
        layout: {
          "symbol-placement": "line",
          "symbol-spacing": 320,
          "text-field": ["get", "name"],
          "text-font": ["Klokantech Noto Sans CJK Regular"],
          "text-size": ["interpolate", ["linear"], ["zoom"], 14, 10, 18, 13],
          "text-max-angle": 30,
        },
        paint: {
          "text-color": "#66625c",
          "text-halo-color": "#ffffff",
          "text-halo-width": 1.4,
        },
      },
      {
        id: "park-label",
        type: "symbol",
        ...sourceLayer("park"),
        minzoom: 14,
        filter: ["has", "name"],
        layout: {
          "text-field": ["get", "name"],
          "text-font": ["Klokantech Noto Sans CJK Regular"],
          "text-size": 11,
        },
        paint: {
          "text-color": "#64735b",
          "text-halo-color": "#f7f7f4",
          "text-halo-width": 1.2,
        },
      },
      {
        id: "building-label",
        type: "symbol",
        ...sourceLayer("building"),
        minzoom: 16.3,
        filter: ["has", "name"],
        layout: {
          "text-field": ["get", "name"],
          "text-font": ["Klokantech Noto Sans CJK Regular"],
          "text-size": 10.5,
          "text-max-width": 8,
        },
        paint: {
          "text-color": "#6f6a63",
          "text-halo-color": "#f7f7f4",
          "text-halo-width": 1.2,
        },
      },
    ],
  };
}
